/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PPollIdRouteImport } from './routes/p/$pollId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as ApiPollsRouteImport } from './routes/api/polls'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiLiveRouteImport } from './routes/api/live'
import { Route as ApiPollsVoteRouteImport } from './routes/api/polls.vote'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PPollIdRoute = PPollIdRouteImport.update({
  id: '/p/$pollId',
  path: '/p/$pollId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPollsRoute = ApiPollsRouteImport.update({
  id: '/api/polls',
  path: '/api/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPollsVoteRoute = ApiPollsVoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => ApiPollsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/live': typeof ApiLiveRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/polls': typeof ApiPollsRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/p/$pollId': typeof PPollIdRoute
  '/api/polls/vote': typeof ApiPollsVoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/live': typeof ApiLiveRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/polls': typeof ApiPollsRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/p/$pollId': typeof PPollIdRoute
  '/api/polls/vote': typeof ApiPollsVoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/live': typeof ApiLiveRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/polls': typeof ApiPollsRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/p/$pollId': typeof PPollIdRoute
  '/api/polls/vote': typeof ApiPollsVoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/live'
    | '/api/mcp'
    | '/api/polls'
    | '/demo/tanstack-query'
    | '/p/$pollId'
    | '/api/polls/vote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/live'
    | '/api/mcp'
    | '/api/polls'
    | '/demo/tanstack-query'
    | '/p/$pollId'
    | '/api/polls/vote'
  id:
    | '__root__'
    | '/'
    | '/api/live'
    | '/api/mcp'
    | '/api/polls'
    | '/demo/tanstack-query'
    | '/p/$pollId'
    | '/api/polls/vote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiLiveRoute: typeof ApiLiveRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiPollsRoute: typeof ApiPollsRouteWithChildren
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  PPollIdRoute: typeof PPollIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$pollId': {
      id: '/p/$pollId'
      path: '/p/$pollId'
      fullPath: '/p/$pollId'
      preLoaderRoute: typeof PPollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polls': {
      id: '/api/polls'
      path: '/api/polls'
      fullPath: '/api/polls'
      preLoaderRoute: typeof ApiPollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polls/vote': {
      id: '/api/polls/vote'
      path: '/vote'
      fullPath: '/api/polls/vote'
      preLoaderRoute: typeof ApiPollsVoteRouteImport
      parentRoute: typeof ApiPollsRoute
    }
  }
}

interface ApiPollsRouteChildren {
  ApiPollsVoteRoute: typeof ApiPollsVoteRoute
}

const ApiPollsRouteChildren: ApiPollsRouteChildren = {
  ApiPollsVoteRoute: ApiPollsVoteRoute,
}

const ApiPollsRouteWithChildren = ApiPollsRoute._addFileChildren(
  ApiPollsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiLiveRoute: ApiLiveRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiPollsRoute: ApiPollsRouteWithChildren,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  PPollIdRoute: PPollIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
